# Generated by Django 6.0.3 on 2026-03-29 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_libros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editora',
            old_name='nombre',
            new_name='nombre_editora',
        ),
    ]
