# Generated by Django 6.0.3 on 2026-03-29 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_libros', '0003_rename_libros_fields_to_camelcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoGenero', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='editora',
            old_name='nombre_editora',
            new_name='nombreEditora',
        ),
        migrations.AddField(
            model_name='libros',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo_libros.genero'),
        ),
    ]
