# Generated by Django 6.0.3 on 2026-03-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_libros', '0004_genero_rename_nombre_editora_editora_nombreeditora_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genero',
            new_name='Generos',
        ),
    ]
